version: '3'

services:
    python:
        image: python:3.6
        volumes:
            - ./:/team-homepage
        ports:
            - 8000:8000
        command: bash -c "cd team-homepage && pip install -r requirements.txt && python manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
