# Generated by Django 2.2.15 on 2020-08-09 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GMotorsports', '0003_donatepage_jointeampage_subteampage'),
    ]

    operations = [
        migrations.AddField(
            model_name='jointeampage',
            name='subteam',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
