# Generated by Django 2.2.15 on 2020-08-09 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GMotorsports', '0004_jointeampage_subteam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jointeampage',
            name='subteam',
        ),
        migrations.AddField(
            model_name='subteampage',
            name='subteam',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
