name: Docker Image Build/Push to MAIN

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: Checkout code
    
    - uses: mr-smithers-excellent/docker-build-push@v5
      name: Build and push docker image
      with:
        image: //dockerhub
        tag: PROD
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
