name: Docker Image Build/Push to Feature Branch.

on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches-ignore:
      - main

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: Checkout code
    
    - uses: mr-smithers-excellent/docker-build-push@v5
      name: Build and push docker image
      with:
        image: //dockerhub
        tag: FEAT
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
